xgb:
  max_depth: 3
  eta: 0.1
  min_child_weight: 1
  subsample: 0.8
  colsample_bytree: 0.8
  scale_pos_weight: 1

mlp:
    hidden_units: 10
    activation: relu
    optimizer: adam
    epochs: 10
    batch_size: 32
    validation_split: 0.2
    dropout: 0.2
    learning_rate: 0.001
